Fix multiGPU Pytorch MovieLens
NVIDIA-Merlin/NVTabular pull request #1319
Opened 2021-12-14 10:30 UTC by bschifferer

Fix for https://github.com/NVIDIA-Merlin/NVTabular/issues/1290

2021-12-15 21:23 UTC, karlhigley approved these changes

2021-12-16 17:16 UTC, karlhigley commented
rerun tests

2021-12-17 15:40 UTC, jperez999 requested changes

2021-12-17 15:40 UTC, jperez999 commented on examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb
> +      "[1,1]<stderr>:CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
These are errors right? Do we want this showing this?

2021-12-17 15:42 UTC, jperez999 approved these changes

2021-12-22 21:46 UTC, benfred approved these changes

2021-12-30 00:10 UTC, albert17 commented
/blossom-ci

2022-01-04 23:20 UTC, benfred commented
/blossom-ci

2022-01-05 18:56 UTC, merged