Update `Operator.dependencies` to be a property
NVIDIA-Merlin/NVTabular pull request #1431
Opened 2022-03-04 22:07 UTC by karlhigley

Companion PR to NVIDIA-Merlin/core#33 to account for the changes there

2022-03-04 22:13 UTC, karlhigley commented
Tests are failing here because CI is using the latest released version of `merlin-core`, not the one from the corresponding PR

2022-03-07 22:00 UTC, jperez999 requested changes

2022-03-07 23:39 UTC, karlhigley commented on examples/advanced-ops-outbrain/02-ETL-with-NVTabular.ipynb
>    {
Just the property change, will update

2022-03-10 00:25 UTC, benfred approved these changes
lgtm - though we probably should install the latest merlin-core too

2022-03-10 01:47 UTC, karlhigley commented
Superseded by #1441

2022-03-10 01:47 UTC, closed without merging